repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: ["--autofix"]
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
      - id: check-added-large-files

  # - repo: https://github.com/PyCQA/flake8
  #   rev: v4.0.1
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
      # - language_version: python3.8
  # - repo: https://github.com/psf/black
  #   rev: 21.12b0
  #   hooks:
  #     - id: black
  # -   repo: https://github.com/pre-commit/mirrors-mypy
  #     rev: v0.941
  #     hooks:
  #     -   id: mypy
  # - repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257
  #   rev: v0.3.3 # Use the sha / tag you want to point at
  #   hooks:
  #     - id: pep257
  # - repo: https://github.com/pycqa/isort
  #   rev: v5.10.1
  #   hooks:
  #     - id: isort
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v2.31.1
  #   hooks:
  #     - id: pyupgrade
  #       args: [--py37-plus]
  - repo: https://github.com/asottile/dead
    rev: v1.4.0
    hooks:
      -  id: dead
  - repo:  https://github.com/milin/giticket
    rev: v1.3
    hooks:
    - id:  giticket
  - repo:  https://github.com/PyCQA/docformatter
    rev: v1.4
    hooks:
    - id: docformatter
      name: docformatter
      description: 'Formats docstrings to follow PEP 257.'
      entry: docformatter
      args: [-i]
      language: python
      types: [python]
  # - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  #   rev: v2.4.0
  #   hooks:
  #   - id: editorconfig-checker
  #     alias: ec
  - repo: https://github.com/dannysepler/rm_unneeded_f_str
    rev: v0.1.0
    hooks:
    - id: rm-unneeded-f-str
  # - repo: https://github.com/hadialqattan/pycln
  #   rev: v0.0.1-beta.3
  #   hooks:
  #     - id: pycln
  #       args: [--config=pyproject.toml]
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.5.4
  #   hooks:
  #     - id: isort
  #       files: "\\.(py)$"
  #       args: [--settings-path=pyproject.toml]
